# This is a basic workflow to help you get check multiple jobs has parelel Runs with Actions


name: Workflowone

on:
  workflow_dispatch:  
  # push:\\\
  

concurrency:
  group: ci_workflow_group
  cancel-in-progress: false
# concurrency: 
#   group: ${{ github.head_ref ||  github.ref }}

jobs:
  job1:
    runs-on: self-hosted
    
    steps:
      - name: Step 1
        run: |
         echo "This is Workflow 1 - Job 1"
         sleep 10 

  job2:
    runs-on: self-hosted
   # needs: job1
    steps:
      - name: Step 2
        run: |
         echo "This is Workflow 1 - Job 2"
         sleep 10

  job3:
    runs-on: self-hosted
   # needs: job2
    steps:
      - name: Step 3
        run: echo "This is Workflow 1 - Job 3"

  job4:
    runs-on: self-hosted
   # needs: job2
    steps:
      - name: Step 4
        run: echo "This is Workflow 1 - Job 4"
