---
name: Workflow 1
on:
  workflow_dispatch: null
concurrency:
  group: ci_workflow_group
  cancel-in-progress: false
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Step 1
        continue-on-error: false
        run: |
          echo "This is Workflow 1 - Job 1"
          sleep 10 
          exit 1
      - name: Step 2
       
        run: |
          echo "This is Workflow 1 - Job 1"

          sleep 10 
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: |
          echo "This is Workflow 1 - Job 2"
          sleep 10
  job3:
    runs-on: windows-latest
    steps:
      - name: Step 3
        run: echo "This is Workflow 1 - Job 3"
