name: Workflow 1

on:
  workflow_dispatch:  
  # push:

concurrency:
  group: ci_workflow_group
  cancel-in-progress: false

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Step 1
        run: |
         echo "This is Workflow 1 - Job 1"
         sleep 10 
  job2:
    runs-on: ubuntu-latest
 #   needs: job1
    steps:
      - name: Step 2
        run: |
         echo "This is Workflow 1 - Job 2"
         sleep 10
  job3:
    runs-on: windows-latest
 #   needs: [job1, job2]
    steps:
      - name: Step 3
        run: echo "This is Workflow 1 - Job 3"

 #  job4:
 #    runs-on: self-hosted
 # #   needs: [job1, job2, job3]
 #    steps:
 #      - name: Step 4
 #        run: echo "This is Workflow 1 - Job 4"
